apiVersion: apps/v1
kind: Deployment
metadata:
  name: questions-api
  namespace: certimatch
spec:
  selector:
    matchLabels:
      app: questions-api
  replicas: 1
  template:
    metadata:
      labels:
        app: questions-api
    spec:
      containers:
        - name: questions-api
          image: localhost:5001/questions-api:latest
          ports:
            - containerPort: 8887
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: certimatch-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: certimatch-secrets
                  key: password
            - name: DB_URI
              value: "postgres.certimatch:5432/certimatch" # Replace with correct DB URI
      imagePullSecrets:
        - name: regcred