apiVersion: v1
kind: Service
metadata:
  name: questions-api
  namespace: certimatch
spec:
  selector:
    app: questions-api
  ports:
    - name: http
      port: 8887
      protocol: TCP
      targetPort: 8887
  type: LoadBalancer
  loadBalancerIP: 172.21.118.12