apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: certimatch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
