apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: certimatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "$DB_USERNAME"
        - name: POSTGRES_PASSWORD
          value: "$DB_PASSWORD"
        - name: POSTGRES_DB
          value: "certimatch"
        volumeMounts:
        - name: database-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-pvc
